{% set name = "openpmd-viewer" %}
{% set version = "1.0.0" %}
{% set build = 1 %}
{% set sha256 = "9b73c15a3a7058a253ca667b90fdcb955144731f553d9222aebd5b82a898caae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/openPMD/openPMD-viewer/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - h5py
    - matplotlib-base
    - numba
    - numpy
    - python
    - scipy
    - tqdm
    # slider
    - ipywidgets
    # openPMD_notebook command
    - jupyter
    # examples
    - python-wget

test:
  imports:
    - openpmd_viewer

about:
  home: https://www.openPMD.org
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: "Python visualization tools for openPMD files"

  description: |
    This package contains a set of tools to load and visualize the
    contents of a set of openPMD files (typically, a timeseries).
    The routines of openPMD-viewer can be used in two ways:
    (1) Use the Python API, in order to write a script that loads
        the data and produces a set of pre-defined plots.
    (2) Use the interactive GUI inside the Jupyter Notebook, in
        order to interactively visualize the data.
  dev_url: https://github.com/openPMD/openPMD-viewer

extra:
  recipe-maintainers:
    - ax3l
    - RemiLehe
